Import("*")

# Use the 'standard' hammersley points when running tests.
t = env.AddPythonTest("test_basics.py")
env.Depends(t, [shape_volume_exe, "../../../test_data/hammersley"] + Glob("data/in/*"))
