Import("*")
import glob
import logging

apLib = mesaacLibs["alglib_net.apLib"]
svdLib = mesaacLibs["alglib_net.svdLib"]
env = env.Clone()
env.Append(
  CPPPATH=["#src/lib/svd", "#src/lib/svd/libs"],
  LIBS=[mesaacLibs["mesaac_mol"], mesaacLibs["mesaac_shape"], apLib, svdLib],
)

shape_filter_by_radius_exe = env.Installable("shape_filter_by_radius")
SConscript(dirs=["test"], exports="env shape_filter_by_radius_exe")
