Import("*")

env = env.Clone()
env.Prepend(
    LIBS=[mesaMolLib]
)
env.Append(
    LIBS=["cppunit"]
)

testData = Glob("data/in/*") + Glob("data/actual/*")
for unittest in Split("atom bond mol sdreader sdwriter"):
    name = "test_" + unittest
    p = env.AddUnitTestProg(name)
    # Some tests need no input data, but make them all dependent on the
    # input test data.
    env.Depends(p, testData)