Import("*")
import logging
import os

apLib = mesaacLibs['alglib_net.apLib']
svdLib = mesaacLibs['alglib_net.svdLib']

canBuild = env["HAVE_BOOST"]

if not canBuild:
    logging.warn("Cannot build in %s -- Boost is needed" % os.getcwd())
else:
    env = env.Clone(
    )
    env.Append(
      CPPFLAGS=Split("-DHAVE_BOOST=1"),
      CPPPATH=Split("#src/lib/svd #src/lib/svd/libs") + [env["BOOST_CPPPATH"]],
      LIBPATH=[env["BOOST_LIBPATH"]],
      LIBS=[apLib, svdLib],
    )

libSrcs = Split("vol_box.cpp axis_aligner.cpp hammersley.cpp fingerprinter.cpp")

l = mesaShapeLib = env.StaticLibrary("mesaac_shape_eigen", libSrcs)
env.Default(l)
Alias("binaries", mesaShapeLib)
Alias("libs", mesaShapeLib)

installer = env.Install(env["libDir"], l)
Alias("install", installer)

# To better test linking via the test subdir, would it be better
# to pre-inject mesaShapeLib into mesaacLibs?
SConscript("test/SConscript", exports="env mesaacLibs mesaShapeLib")

Return("mesaShapeLib")
