#!/bin/bash
cat <<EOF1
=======================================================================
Running regression tests.
-----------------------------------------------------------------------
EOF1

set -e
BI=$(hg root)/../../include/build_info.h

# Get the license expiration info from the last build.
function get_expires() {
    python <<EOF3
import os, datetime
perpetual = 0
year = datetime.date.today().year
month = datetime.date.today().month
inf = open(os.path.abspath("${BI}"))
for line in inf:
    if "LICENSE_PERPETUAL" in line:
        perpetual = int(line.split()[-1])
    elif "LICENSE_EXPIRES_YEAR" in line:
        year = int(line.split()[-1])
    elif "LICENSE_EXPIRES_MONTH" in line:
        month = int(line.split()[-1])
if perpetual:
    print("never")
else:
    print("%s/%s" % (year, month))
EOF3
}
cd $(hg root)/test && scons -u expires=$(get_expires) .

cat <<EOF2
-----------------------------------------------------------------------
Regression tests passed.
=======================================================================
EOF2
