Import("*")
import glob

env = env.Clone()
env.Append(
    CPPPATH=". libs".split(),
    LIBPATH=". libs".split(),
)

apLib = SConscript("libs/SConscript", exports="env")
Default(apLib)

svdSrcs = Glob("*.cpp")
svdLib = env.Library("svd", svdSrcs)
Default(svdLib)

SConscript("tests/SConscript", exports="env apLib svdLib")

mesaacLibs['alglib_net.apLib'] = apLib
mesaacLibs['alglib_net.svdLib'] = svdLib

Return ("apLib svdLib")

