Import("*")

env = env.Clone()

libSrcs = Split("mol.cpp atom.cpp bond.cpp element_info.cpp io/sdreader.cpp io/sdwriter.cpp")

l = mesaMolLib = env.StaticLibrary("mesaac_mol", libSrcs)
env.Default(l)
Alias("binaries", mesaMolLib)
Alias("libs", mesaMolLib)

installer = env.Install(env["libDir"], l)
Alias("install", installer)

# To better test linking via the test subdir, would it be better
# to pre-inject mesaMolLib into mesaacLibs?
SConscript("test/SConscript", exports="env mesaMolLib")

Return("mesaMolLib")
